### ISSUE TITLE
NSDateFormatter performance

### ISSUE THREAD

**Issue by pankkor** [lmirosevic/GBToolbox#5]
@lmirosevic 
```iso8601String``` is damn slow due to ```NSDateFormatter *dateFormatter = [NSDateFormatter new];```
There are 2 solutions:
1. Cache NSDateFormatter into a static var. I think there is no point in caching into ```threadDictionary``` as from ios 7 NSDateFormatter should be thread-safe.
2. Use something faster. My benchmarks showed that this is the fastest solution:
```
-(NSString *)iso8601String {
    time_t time = (time_t)[self timeIntervalSince1970];
    struct tm tm;
    gmtime_r(&time, &tm);
    
    char buffer[30];
    size_t length = strftime(buffer, sizeof(buffer), "%Y-%m-%dT%H:%M:%S%z", &tm);
    
    return [[NSString alloc] initWithBytes:buffer length:length encoding:NSUTF8StringEncoding];
}
```

Same for ```dateWithISO8601String```
Can cache 2 NSDateFormats or use something like:
```
time_t t;
struct tm tm;
strptime(string.UTF8String, "%Y-%m-%dT%H:%M:%S%z", &tm);
tm.tm_isdst = -1;
t = mktime(&tm);
return [NSDate dateWithTimeIntervalSince1970:t + [[NSTimeZone localTimeZone] secondsFromGMT]];
```

Which solution do you prefer?

**Comment by lmirosevic** [comment]
Thanks for the PR, I've merged it!

**Comment by pankkor** [comment]
@lmirosevic thank!
